<?xml version="1.0" encoding="utf-8"?>
<testsuites>
    <testsuite name="XUnitSample.DataDriven" hostname="GFOIDL-PC-2018" package=".NET Core" id="0" tests="3" failures="1" errors="0" skipped="0" time="0.004" timestamp="2019-04-18T18:24:24">
        <properties />
        <testcase name="XUnitSample.DataDriven.Two_pass_one_fails(arg: 0)" classname="XUnitSample.DataDriven" time="0.001" />
        <testcase name="XUnitSample.DataDriven.Two_pass_one_fails(arg: 2)" classname="XUnitSample.DataDriven" time="0.002" />
        <testcase name="XUnitSample.DataDriven.Two_pass_one_fails(arg: 1)" classname="XUnitSample.DataDriven" time="0.001">
            <failure message="Failing for demo purposes&#xD;&#xA;Expected: True&#xD;&#xA;Actual:   False" type="not specified">   at XUnitSample.DataDriven.Two_pass_one_fails(Int32 arg) in D:\Work-Git\github\Mini\trx2junit\samples\XUnitSample\DataDriven.cs:line 17</failure>
        </testcase>
        <system-out />
        <system-err />
    </testsuite>
    <testsuite name="XUnitSample" hostname="GFOIDL-PC-2018" package=".NET Core" id="1" tests="2" failures="1" errors="0" skipped="0" time="1.010" timestamp="2019-04-18T18:24:24">
        <properties />
        <testcase name="XUnitSample.DataDriven.Failing_test" classname="XUnitSample" time="0.003">
            <failure message="Failing for demo purposes&#xD;&#xA;Expected: True&#xD;&#xA;Actual:   False" type="not specified">   at XUnitSample.DataDriven.Failing_test() in D:\Work-Git\github\Mini\trx2junit\samples\XUnitSample\DataDriven.cs:line 26</failure>
        </testcase>
        <testcase name="XUnitSample.DataDriven.Slow_test" classname="XUnitSample" time="1.007" />
        <system-out />
        <system-err />
    </testsuite>
</testsuites>
